In [11]:
import pandas as pd

In [12]:
phish = pd.read_csv('phishing_url_dataset.csv')

In [13]:
phish.head(8)

,url_length,valid_url,at_symbol,sensitive_words_count,path_length,isHttps,nb_dots,nb_hyphens,nb_and,nb_or,nb_www,nb_com,nb_underscore,target
0,42,0,0,0,20,0,2,0,0,0,1,1,0,0
1,73,0,0,0,52,0,5,0,0,0,0,1,0,0
2,73,0,0,0,52,0,5,0,0,0,0,1,0,0
3,73,0,0,0,52,0,5,1,0,1,0,1,0,0
4,73,0,0,0,52,0,5,0,0,0,0,1,0,0
5,73,0,0,0,52,0,5,0,0,0,0,1,0,0
6,73,0,0,0,52,0,5,1,0,1,0,1,0,0
7,36,0,0,0,0,1,4,0,0,0,0,0,0,0

In [14]:
phish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2488 entries, 0 to 2487
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url_length             2488 non-null   int64
 1   valid_url              2488 non-null   int64
 2   at_symbol              2488 non-null   int64
 3   sensitive_words_count  2488 non-null   int64
 4   path_length            2488 non-null   int64
 5   isHttps                2488 non-null   int64
 6   nb_dots                2488 non-null   int64
 7   nb_hyphens             2488 non-null   int64
 8   nb_and                 2488 non-null   int64
 9   nb_or                  2488 non-null   int64
 10  nb_www                 2488 non-null   int64
 11  nb_com                 2488 non-null   int64
 12  nb_underscore          2488 non-null   int64
 13  target                 2488 non-null   int64
dtypes: int64(14)
memory usage: 272.3 KB

In [15]:
phish.shape

(2488, 14)

In [16]:
phish.isnull().sum()

url_length               0
valid_url                0
at_symbol                0
sensitive_words_count    0
path_length              0
isHttps                  0
nb_dots                  0
nb_hyphens               0
nb_and                   0
nb_or                    0
nb_www                   0
nb_com                   0
nb_underscore            0
target                   0
dtype: int64

In [17]:
phish.duplicated().sum()

np.int64(1134)

In [18]:
phish[phish.duplicated()]

,url_length,valid_url,at_symbol,sensitive_words_count,path_length,isHttps,nb_dots,nb_hyphens,nb_and,nb_or,nb_www,nb_com,nb_underscore,target
2,73,0,0,0,52,0,5,0,0,0,0,1,0,0
4,73,0,0,0,52,0,5,0,0,0,0,1,0,0
5,73,0,0,0,52,0,5,0,0,0,0,1,0,0
6,73,0,0,0,52,0,5,1,0,1,0,1,0,0
8,73,0,0,0,52,0,5,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2481,74,1,0,0,0,1,5,0,0,0,0,0,0,1
2484,74,1,0,0,0,1,5,0,0,0,0,0,0,1
2485,74,1,0,0,0,1,5,0,0,0,0,0,1,1
2486,74,1,0,0,0,1,5,0,0,0,0,0,0,1
2487,74,1,0,0,0,1,5,0,0,0,0,0,0,1

In [19]:
phish.drop_duplicates(inplace=True)

In [20]:
phish.shape

(1354, 14)

In [21]:
phish.describe()

,url_length,valid_url,at_symbol,sensitive_words_count,path_length,isHttps,nb_dots,nb_hyphens,nb_and,nb_or,nb_www,nb_com,nb_underscore,target
count,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000,1354.000000
mean,51.794682,0.119645,0.015510,0.150665,15.368538,0.277696,3.953471,0.775480,0.025111,0.262186,0.296160,0.675775,0.154357,0.331610
std,20.093369,0.324666,0.331489,0.408035,19.320939,0.448028,2.165043,1.402075,0.161172,0.505640,0.477305,0.564184,0.575901,0.470966
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,55.000000,0.000000,0.000000,0.000000,2.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,73.000000,0.000000,0.000000,0.000000,33.000000,1.000000,5.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
max,96.000000,1.000000,9.000000,3.000000,85.000000,1.000000,13.000000,10.000000,2.000000,3.000000,2.000000,3.000000,7.000000,1.000000

In [22]:
phish.nunique()

url_length               62
valid_url                 2
at_symbol                 4
sensitive_words_count     4
path_length              59
isHttps                   2
nb_dots                  13
nb_hyphens                9
nb_and                    3
nb_or                     4
nb_www                    3
nb_com                    4
nb_underscore             8
target                    2
dtype: int64

In [23]:
phish.to_csv('phish_cleaned.csv',index=False)

In [24]:
phish.shape

(1354, 14)

In [25]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\altaf alam\desktop\annacaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Altaf Alam\Desktop\Annacaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Altaf Alam\Desktop\Annacaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Altaf Alam\Desktop\Annacaconda\Lib\site-packages)

In [26]:
from ydata_profiling import ProfileReport
prof = ProfileReport(phish)
prof. to_file(output_file = 'output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]
 14%|█▍        | 2/14 [00:00<00:00, 16.63it/s]
 29%|██▊       | 4/14 [00:00<00:00, 16.20it/s]
100%|██████████| 14/14 [00:00<00:00, 37.93it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
phish.to_csv('naya_file.csv')